### ISSUE TITLE
Class 'Hackzilla\PasswordGenerator\Generator\PasswordGenerator' not found

### ISSUE THREAD

**Issue by Soullivaneuh** [hackzilla/password-generator-bundle#14]
The [`hackzilla.password_generator` service](https://github.com/hackzilla/password-generator-bundle/blob/cc6c9fe5f6042cd950656778ccad705ee7feaa89/Resources/config/services.yml#L18-L19) class does not exists.

This broke smoke testing services.

This service should be removed or, at least, dynamically added with a `class_exists` test if it concerns an older generator.

**Comment by hackzilla** [comment]
The class was removed with the 1.0 release, and the service could also be removed.

However it'd probably be best set to default generator as it's as [default generator](https://github.com/hackzilla/password-generator-bundle/blob/0a24924b226dc0caac1120502c48733ec3e031cc/Controller/GeneratorController.php#L71)

**Comment by Soullivaneuh** [comment]
> However it'd probably be best set to default generator as it's as default generator

And which would be the default one?

**Comment by hackzilla** [comment]
Good point.

Probably would make sense to throw an exception, and remove the service.
It would have already been throwing an error, until now.

**Comment by hackzilla** [comment]
Fixed master.

Haven't decided if I'll tag it 1.6 or wait till 2.0

**Comment by Soullivaneuh** [comment]
Depends if the code behaviour is changed. You said getting default generator already throw an error? In this case, could be a minor or a patch. If not, should be a major IMO.

**Comment by hackzilla** [comment]
It threw a fatal error for >=1.0, which is why I'm thinking minor.

**Comment by Soullivaneuh** [comment]
Or, change minimum requirement and push a major.

**Comment by hackzilla** [comment]
Nothing changing the dependancies can help.

password-generator <v1 is incompatible with the password-generator-bundle v1

The fix is in dev-master, and can be included in v1, but it will be in v2.
Unfortunately, as it stands, v2 will be Symfony v2.8+|v3.0

**Comment by Soullivaneuh** [comment]
> The fix is in dev-master, and can be included in v1, but it will be in v2.

Did you plan a release date for v2?

**Comment by hackzilla** [comment]
I planned to leave v2 for a while, just to make sure I've got it right.

It works with the Password Generator App, but then other people maybe using it differently.

I'll have a look at all your suggestions tonight.

**Comment by hackzilla** [comment]
This has now been merged, and is in 1.6 and 2.0
