### ISSUE TITLE
Branches and composer

### ISSUE THREAD

**Issue by Soullivaneuh** [hackzilla/password-generator-bundle#16]
Some suggestions:

1. Master should be for 2.x and a 1.x branch should be created.
2. Use branch alias on composer to specify under development version.

For the second one, this will permit to be more clear against Packagist and permit users to get 2.x version even if it's not stable yet.

See: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/blob/befd684492a682aaeece0370594e6649b7b03087/composer.json#L40

**Comment by hackzilla** [comment]
Branch aliases have been setup and v2 has now been merged into master.
