### ISSUE TITLE
Password has number not respected

### ISSUE THREAD

**Issue by numediaweb** [hackzilla/password-generator-bundle#30]
As you can see here: it should generate . password with at least a number but it didn't
<img width="678" alt="Screenshot 2019-03-22 at 11 59 50" src="https://user-images.githubusercontent.com/288614/54818695-24590880-4c9a-11e9-9b16-2f2dd59e8135.png">

**Comment by numediaweb** [comment]
I see: I need to use `hackzilla.password_generator.requirement` service!

**Comment by hackzilla** [comment]
Yeah, the first one is random.
I didn't want to force the overhead of making sure everything was in the final password, if it wasn't actually a requirement.
