### ISSUE TITLE
Could Symfony 5 support be added?

### ISSUE THREAD

**Issue by goodjinny** [hackzilla/password-generator-bundle#32]
Hi! 

Trying install on newest Symfony 5 dist, have a composer error:
`hackzilla/password-generator-bundle 3.0.1 requires symfony/framework-bundle ^2.7|^3.0|^4.0 -> no matching package found`

Could Symfony ^5.0 version support be resolved?

Thanks.

**Comment by hackzilla** [comment]
Allowing Symfony 5 was the first change needed.
I'll get it properly working.

**Comment by hackzilla** [comment]
I've pushed v4.0.0 that seems to work quite nicely with Symfony 5.0.

If you have any issues check out my implementation https://github.com/hackzilla/password-generator-app
