### ISSUE TITLE
Please add support for Symfony 6

### ISSUE THREAD

**Issue by jurvei** [hackzilla/password-generator-bundle#34]
Please add support for Symfony 6, currently the bundle is restricted to ^5.0.

Thank you!

**Comment by hackzilla** [comment]
I've just updated password generator bundle to work with Symfony 6.
When I've had chance to fully test it, I will tag it with a version number.

Let me know if you have any issue with it.

**Comment by jurvei** [comment]
Thank you so much! Works very well in my project.
