### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by czachor** [hackzilla/password-generator-bundle#37]
Current problem:

>     - Root composer.json requires hackzilla/password-generator-bundle ^5.0.1 -> satisfiable by hackzilla/password-generator-bundle[5.0.1].
>     - hackzilla/password-generator-bundle 5.0.1 requires symfony/framework-bundle ^4.0|^5.0|^6.0 -> found symfony/framework-bundle[v4.0.0, ..., v4.4.51, v5.0.0, ..., v5.4.39, v6.0.0, ..., v6.4.7] but it conflicts with your root composer.json require (7.0.*).
> 

I'll send PR for this.

**Comment by hackzilla** [comment]
Thank you for the PR.
I have added a few more changes and tagged it with v6.0.0
